graphite-web:  add pytz and pydjango packages
thoses 2 packages are needed to get graphs in the graphite-web interface

if pytz is missing and when you try to display image you have instead:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/opt/graphite/webapp/graphite/render/views.py", line 56, in renderView
   (graphOptions, requestOptions) = parseOptions(request)
 File "/opt/graphite/webapp/graphite/render/views.py", line 318, in parseOptions
   fromTime = parseATTime('-1d', tzinfo, now)
 File "/opt/graphite/webapp/graphite/render/attime.py", line 48, in parseATTime
   return tzinfo.normalize(parseTimeReference(ref).astimezone(tzinfo) + parseTimeOffset(offset))
AttributeError: 'LocalTimezone' object has no attribute 'normalize'